EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    
    path(_('admin/'), admin.site.urls),
    path(_(''),include("ecomapp.urls",namespace="ecomapp")),
    path('order/',include('orderapp.urls',namespace="orderapp")),
    path('user/',include('UserApp.urls',namespace="UserApp")),
    path("product/",include("product.urls",namespace="product")),
        
    )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from UserApp.views import user_logout, user_login, user_register, user_update, user_password,usercomment, comment_delete
from UserApp.views import usrprofiledata
app_name='UserApp'

urlpatterns = [
    path('logout/',user_logout, name='user_logout' ),
    path('login/',user_login, name='user_login' ),
    path('register/',user_register, name='user_register' ),
    path('userprofile/',usrprofiledata, name='userprofile' ),
    path('user_update/',user_update, name='user_update' ),
    path('password_update/',user_password, name='user_password' ),
    path('user_comment/',usercomment, name='usercomment' ),
    path('comment_delete/<int:id>/',comment_delete, name='comment_delete' ),
]

ecomapp/urls.py
from django.urls import path

from .views import *

app_name= "ecomapp"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("contact/",contact, name="coantact_dat"),
    path("product/<slug:slug>/", SingleProductView.as_view(), name="product_single"),
    path("product/<int:id>/<slug:slug>/", category_product, name="category_product"),
    path("search/",searchview,name="searchview"),
    path("faq/",Faq_details,name="Faq_details"),
    path("send/",send,name="send"),
    path("offers/", OffersView.as_view(), name= "offers"), #for laptops and TV
    path("offers2/", OffersView2.as_view(), name= "offers2"), #OffersView2
    path("offers3/",OffersView3.as_view(), name="offers3"), # for home appliances  
    path("all-products/",all_product_view,name="allproducts"),   #to show All Laptops
    path("all-products2/",all_product_view2,name="allproducts2"),   #to show All TVs
    path("all-products3/",all_product_view3,name="allproducts3"),   #to show All home appliances 
    path("all-products4/",all_product_view4,name="allproducts4"),   #to show All mobiles
    path("all-products5/",all_product_view5,name="allproducts5"),   #to show All  tablets
    path("all-products6/",all_product_view6,name="allproducts6"),   #to show All bestseller
    path("all-products7/",all_product_view7,name="allproducts7"),   #to show All fashion
    path("all-products8/",all_product_view8,name="allproducts8"),   #to show All tools
    
    
]

orderapp/urls.py
from django.urls import path

from orderapp.views import (Add_to_Shoping_cart,
OrderCart,Order_showing, Order_Product_showing,
cart_details, cart_delete, user_order_details, userorderproduct_details)

app_name="orderapp"

urlpatterns=[
    path('addingcart/<int:id>/', Add_to_Shoping_cart, name='Add_to_Shoping_cart'),
    path("cart_details/" ,cart_details, name="cart_details"),
    path('cart_delete/<int:id>/', cart_delete, name='cart_delete'),
    path("order_cart/",OrderCart,name="OrderCart"),
    path("orderlist",Order_showing,name="orderlist"),
    path('OrderProduct/', Order_Product_showing, name="orderproduct"),
    path('OrderDetails/<int:id>/',user_order_details,name='user_order_details'),
    path('OrderproductDetails/<int:id>/<int:oid>/',userorderproduct_details,name='userorderproduct_details'),
    
    
]

orderapp/models.py
from django.db import models
from product .models import *
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from django_countries.fields import CountryField

# Create your models here.

class ShopCart(models.Model):
    product= models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField()


    def price(self):
        if self.product.discount_price:

           return self.product.discount_price
        else:
            return self.product.price
    @property
    def amount(self):
        if self.product.discount_price:
            
           return self.quantity*self.product.discount_price
        else:
            return self.quantity*self.product .price


    def __str__(self):
        return self.product.title

class ShopingCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('Onshiping', 'Onshiping'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled')
            )
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    first_name= models.CharField(max_length=200)  
    last_name=models.CharField(max_length=200)       
    code=models.CharField(max_length=15,editable=False) 
    phone=models.CharField(max_length=200,blank=True, null=True)  
    address=models.CharField(max_length=200)   
    city=models.CharField(max_length=200)  
    country=models.CharField(max_length=200,null=True)
    total=models.FloatField()
    status = models.CharField(choices=STATUS, max_length=20, default='New')
    ip = models.CharField(max_length=200, blank=True)
    transaction_id = models.CharField(max_length=200, blank=True)
    transaction_image = models.ImageField(
        upload_to='transaction_image/', blank=True)
    adminnote = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

    def image_tag(self):
        return mark_safe('<img src="{}" heights="50" width="40" />'.format(self.transaction_image.url))
    image_tag.short_description = 'Image'



class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name',
                  'phone', 'address', 'city', 'country', 'transaction_id', 'transaction_image']



class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Cancelled', 'Cancelled')
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    seller = models.CharField(max_length=200, blank=True)
    quantity = models.PositiveIntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title
    @property
    def amountnow(self):
        if self.product .discount_price:
            
           return self.quantity*self.product.discount_price
        else:
            return self.quantity*self.product.price                  

orderapp/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect, reverse
from django.views.generic import ListView, TemplateView , DetailView , View, CreateView, FormView
from product.models import Category, Product, Images
from django.contrib import messages
from orderapp .models import *
from ecomapp.models import Setting, ContactMessage
from ecomapp.models import *
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from UserApp.models import UserProfile

# Create your views here.


@login_required()
def Add_to_Shoping_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    checking = ShopCart.objects.filter(
        product_id=id, user_id=current_user.id)
        
    if checking:
        control = 1
    else:
        control = 0

    if request.method == "POST":
        form = ShopingCartForm(request.POST)
        if form.is_valid():
            if control == 1:
                data = ShopCart.objects.get(
                    product_id=id, user_id=current_user.id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, 'Your Product  has been added')
        return HttpResponseRedirect(url)
    else:
        if control == 1:
            data = ShopCart.objects.filter(
            product_id = id, user_id=current_user.id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            
            data.quantity = 1
            data.save()
        messages.success(request, 'Your  product has been added')
        return HttpResponseRedirect(url)


def cart_details(request):
    
    current_user = request.user
    category= Category.objects.all()
    setting = Setting.objects.get(id=1)
    cart_product= ShopCart.objects.filter(user_id=current_user.id)
    
    total_amount = 0
    
    for p in cart_product:
        
        if p.product.discount_price:
            total_amount += p.product.discount_price * p.quantity
        elif p.product.price:
            total_amount += p.product.price * p.quantity

    context = {"category":category,
                "setting":setting,
                "cart_product":cart_product,
                "total_amount":total_amount,
                
            }
    return render(request,"cart_details.html", context)


@login_required()
def cart_delete(request,id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    cart_product= ShopCart.objects.filter(id=id,user_id=current_user.id)
    cart_product.delete()
    messages.warning(request, 'Your  product has been deleted successfully!!')
    return HttpResponseRedirect(url)




@login_required()
def OrderCart(request):
    current_user=request.user
    
    shoping_cart=ShopCart.objects.filter(user_id=current_user.id)
    totalamount=0
    for rs in shoping_cart:
        if rs.product.discount_price:
            totalamount += rs.product.discount_price * rs.quantity
        elif rs.product.price:
            totalamount += rs.product.price * rs.quantity
    if request.method=="POST":
        form=OrderForm(request.POST,request.FILES)
        if form.is_valid():
            dat =Order()
            dat.first_name=form.cleaned_data["first_name"]
            dat.last_name = form.cleaned_data['last_name']
            dat.address = form.cleaned_data['address']
            dat.city = form.cleaned_data['city']
            dat.phone = form.cleaned_data['phone']
            dat.country = form.cleaned_data['country']
            dat.transaction_id = form.cleaned_data['transaction_id']
            dat.transaction_image = form.cleaned_data['transaction_image']
            dat.user_id = current_user.id
            
            dat.total = totalamount
            dat.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(length=12, allowed_chars='ABCDE01234')  # random cod
            dat.code = ordercode
            dat.save()
            for rs in shoping_cart:
                data = OrderProduct()
                data.order_id = dat.id
                data.product_id = rs.product_id
                
                data.user_id = current_user.id
                data.quantity = rs.quantity
                if rs.product.discount_price:
                    data.price = rs.product.discount_price
                else:
                    data.price = rs.product.price 
                
                data.amount = rs.amount
                data.save()

                product = Product.objects.get(id=rs.product_id)
                
                
                product.amount -= rs.quantity
                
                product.save()
                
            # Now remove all oder data from the shoping cart
            ShopCart.objects.filter(user_id=current_user.id).delete()
            # request.session['cart_item']=0
            messages.success(request, 'Your order has been completed')
            category = Category.objects.all()
            setting = Setting.objects.get(id=1)
            context = {
                # 'category':category,
                'ordercode': ordercode,
                'category': category,
                'setting': setting,
            }

            return render(request, 'order_completed.html', context)
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/order_cart")
    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    total_amount = 0
    for p in shoping_cart:
        if p.product.discount_price:
            total_amount += p.product.discount_price * p.quantity
        else:
            total_amount += p.product.price * p.quantity
        
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)

    context = {
        # 'category':category,
        'shoping_cart': shoping_cart,
        'totalamount': totalamount,
        'profile': profile,
        'form': form,
        'category': category,
        'setting': setting,
        'total_amount': total_amount
    }
    return render(request, 'order_form.html', context)

@login_required()
def Order_showing(request):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user = request.user
    orders = Order.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'setting': setting,
        'orders': orders

    }

    return render(request, 'user_order_showing.html', context)

@login_required()
def Order_Product_showing(request):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user = request.user
    order_product = OrderProduct.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'setting': setting,
        'order_product': order_product

    }

    return render(request, 'OrderProducList.html', context)



@login_required()
def user_order_details(request,id):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user = request.user
    orders = Order.objects.get(user_id=current_user.id,id=id)
    order_products = OrderProduct.objects.filter(order_id=id)
    context = {
        'category': category,
        'setting': setting,
        'orders': orders,
        'order_products':order_products,

    }

    return render(request,'user_order_details.html', context)


@login_required()
def userorderproduct_details(request,id,oid):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user = request.user
    orders = Order.objects.get(user_id=current_user.id,id=oid)
    order_products = OrderProduct.objects.get(user_id=current_user.id,id=id)
    context = {
        'category': category,
        'setting': setting,
        'orders': orders,
        'order_products':order_products,

    }

    return render(request,'user_order_pro_details.html', context)    
    

orderapp/templates/OrderProducList.html
{%extends 'index.html'%}
{% load i18n %}
{%load static%}

{% load crispy_forms_tags %}

{% block titlee %}
Order Showing

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}



<div class="breadcrumb-area">
    <div class="container">
        <div class="breadcrumb-content">
            <ul>
                <li><a href="/">Home</a></li>
                <li class="active">Order Information</li>
            </ul>
        </div>
    </div>
</div>
<!-- Li's Breadcrumb Area End Here -->
<!--Wishlist Area Strat-->
<div class="page-section mb-60">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-3 mb-30">
                <h1 class="font-weight-bold">User Panel</h1>
                {% include 'user_panel.html' %}
                
            </div>

            <div class="col-sm-12 col-md-12 col-lg-9 col-xs-12">
                <form action="#">
                    <div class="table-content table-responsive">
                        <table class="table">
                            <thead>
                                <tr>

                                    <th class="cart-product-name">Username</th>
                                    <th class="li-product-price">Product Image</th>
                                    <th class="li-product-price">Product title</th>
                                    <th class="li-product-stock-status">Price</th>
                                    <th class="li-product-stock-status">Quantity</th>
                                    <th class="li-product-stock-status"> Total Price</th>
                                    
                                    
                                    <th class="li-product-add-cart">Status</th>
                                    <th class="li-product-add-cart">Action</th>

                                    
                                </tr>
                            </thead>
                            <tbody>
                                {% for p in order_product %}
                                <tr>

                                    <td class="li-product-name"><a href="#">{{p.user.username}}</a></td>
                                    <td class="li-product-thumbnail"><a href="#"><img src="{{p.product.ImageUrl}}" style="height:60px; width:60px;"></a></td>
                                    <td class="li-product-price"><span class="amount">EGP{{p.product.title}}</span></td>
                                         {% if p.discount_price %}
                                    
                                    <td class="li-product-stock-status"><span class="in-stock">EGP{{p.discount_price}}</span></td>
                                          {% else %}
                                    <td class="li-product-stock-status"><span class="in-stock">EGP{{p.price}}</span></td>
                                         {% endif %}
                                    
                                    <td class="li-product-price"><span class="amount">{{p.quantity}}</span></td>
                                    <td class="li-product-price"><span class="amount">EGP{{p.amountnow}}</span></td>
                                    
                                    
                                    <td class="li-product-stock-status"><span class="in-stock">{{p.status}}</span>
                                    </td>
                                    <td class="li-product-add-cart"><a href="{%url 'orderapp:userorderproduct_details' id=p.id oid=p.order_id%}">Details</a></td>
                                    

                                   
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock another_content %}
{% block footer %}

{% include "footer.html" %}

{% endblock footer %}

orderapp/templates/order_completed.html
{%extends 'index.html'%}

{%load static%}
{% load i18n %}
{% load crispy_forms_tags %}

{% block titlee %}
Order completed

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}

<div id="breadcrum">
    <div class="container">
        <div>
            <ul class="breadcrumb">
                <li> <a href="{%url 'ecomapp:home'%}">Home</a></li>
                >>
                <li class="active">Completed Order</li>
            </ul>

        </div>

    </div>

</div>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Order Complated</h3>
                    </div>
                  
                    <h2>Dear {{ user.username }} {{  user.last_name }}</h2>
                    <h3>Your order is completed</h3>
                    <h3>Order Code : {{ ordercode }}</h3>
                    <h3>Thank You</h3>
                    <hr>

                </div>

            </div>

        </div>

    </div>


</div>


{% endblock another_content %}




{% block footer %}

{% include "footer.html" %}

{% endblock footer %}

orderapp/templates/order_form.html
{%extends 'index.html'%}

{%load static%}
{% load humanize %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block titlee %}
single product

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}


<!-- Begin Li's Breadcrumb Area -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="breadcrumb-content">
            <ul>
                <li><a href="{% url 'ecomapp:home' %}">Home</a></li>
                <li class="active">Checkout</li>
            </ul>
        </div>
    </div>
</div>
<!-- Li's Breadcrumb Area End Here -->
<!--Checkout Area Strat-->
<div class="checkout-area pt-60 pb-30">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="coupon-accordion">
                    <!--Accordion Start-->
                    <h3>{% trans 'Returning customer?' %}   <span id="showlogin">{% trans 'Click here to login' %} </span></h3>
                    <div id="checkout-login" class="coupon-content">
                        <div class="coupon-info">
                            <p class="coupon-text">Quisque gravida turpis sit amet nulla posuere lacinia. Cras sed
                                est sit amet ipsum luctus.</p>
                            <form action="#">
                                <p class="form-row-first">
                                    <label>Username or email <span class="required">*</span></label>
                                    <input type="text">
                                </p>
                                <p class="form-row-last">
                                    <label>Password <span class="required">*</span></label>
                                    <input type="text">
                                </p>
                                <p class="form-row">
                                    <input value="Login" type="submit">
                                    <label>
                                        <input type="checkbox">
                                        Remember me
                                    </label>
                                </p>
                                <p class="lost-password"><a href="#">Lost your password?</a></p>
                            </form>
                        </div>
                    </div>
                    <!--Accordion End-->
                    <!--Accordion Start-->
                    <h3>{% trans 'Have a coupon?' %} <span id="showcoupon">{% trans 'Click here to enter your code' %} </span></h3>
                    <div id="checkout_coupon" class="coupon-checkout-content">
                        <div class="coupon-info">
                            <form action="#">
                                <p class="checkout-coupon">
                                    <input placeholder="Coupon code" type="text">
                                    <input value="Apply Coupon" type="submit">
                                </p>
                            </form>
                        </div>
                    </div>
                    <!--Accordion End-->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-12">
                <form method='POST' enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="checkbox-form">
                        <h3>{% trans 'Billing Details' %}</h3>
                        <div class="row">

                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>{% trans 'First Name' %} <span class="required">*</span></label>
                                    <input placeholder="" type="text" value="{{user.first_name}}" name="first_name">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>{% trans 'Last Name' %} <span class="required">*</span></label>
                                    <input placeholder="" type="text" value="{{user.last_name}}" name="last_name">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>{% trans ' Your Address' %} <span class="required">*</span></label>
                                    <input placeholder="Street address" type="text" value="{{profile.address}}"
                                        name="address">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="checkout-form-list">
                                    <label>{% trans 'Town / City' %} <span class="required">*</span></label>
                                    <input type="text" value="{{profile.city}}" name="city">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="country-select clearfix">
                                    <label>{% trans 'Country' %} <span class="required">*</span></label>
                                    <select class="nice-select wide" value="{{profile.country}}" name="country">
                                        <option data-display="Egypt">Egypt</option>
                                        <option value="uk">London</option>
                                        <option value="rou">Romania</option>
                                        <option value="fr">French</option>
                                        <option value="de">Germany</option>
                                        <option value="aus">Australia</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>{% trans 'Phone' %} <span class="required">*</span></label>
                                    <input type="text" value="{{profile.phone}}" name="phone">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="checkout-form-list">
                                    <label>{% trans 'Amount' %} <span class="required">*</span></label>
                                    <input type="text" value="{{total_amount}}" name="holder" readonly>
                                </div>
                            </div>

                        </div>
                        <div class="order-button-payment">
                            <input value="Place order" type="submit">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-12">
                <div class="your-order">
                    <h3>{% trans 'Your order' %}</h3>
                    <div class="your-order-table table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="cart-product-name">{% trans 'Product' %}</th>
                                    <th class="cart-product-total">{% trans 'Total' %}</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% for p in shoping_cart %}



                                <tr class="cart_item">
                                    <td class="cart-product-name">{{p.product.title}}<strong class="product-quantity">
                                            × {{p.quantity}}</strong></td>
                                    <td class="cart-product-total"><span class="amount">EGP{{p.amount|intcomma}}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr class="cart-subtotal">
                                    <th>{% trans 'Cart Subtotal' %}</th>
                                    <td><span class="amount">EGP{{total_amount}}</span></td>
                                </tr>
                                <tr class="order-total">
                                    <th>{% trans 'Order Total' %}</th>
                                    <td><strong><span class="amount">EGP{{total_amount}}</span></strong></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!--Checkout Area End-->

{% endblock another_content %}




{% block footer %}

{% include "footer.html" %}

{% endblock footer %}