EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    
    path(_('admin/'), admin.site.urls),
    path(_(''),include("ecomapp.urls",namespace="ecomapp")),
    path('order/',include('orderapp.urls',namespace="orderapp")),
    path('user/',include('UserApp.urls',namespace="UserApp")),
    path("product/",include("product.urls",namespace="product")),
        
    )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from UserApp.views import user_logout, user_login, user_register, user_update, user_password,usercomment, comment_delete
from UserApp.views import usrprofiledata
app_name='UserApp'

urlpatterns = [
    path('logout/',user_logout, name='user_logout' ),
    path('login/',user_login, name='user_login' ),
    path('register/',user_register, name='user_register' ),
    path('userprofile/',usrprofiledata, name='userprofile' ),
    path('user_update/',user_update, name='user_update' ),
    path('password_update/',user_password, name='user_password' ),
    path('user_comment/',usercomment, name='usercomment' ),
    path('comment_delete/<int:id>/',comment_delete, name='comment_delete' ),
]

ecomapp/urls.py
from django.urls import path

from .views import *

app_name= "ecomapp"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("contact/",contact, name="coantact_dat"),
    path("product/<slug:slug>/", SingleProductView.as_view(), name="product_single"),
    path("product/<int:id>/<slug:slug>/", category_product, name="category_product"),
    path("search/",searchview,name="searchview"),
    path("faq/",Faq_details,name="Faq_details"),
    path("send/",send,name="send"),
    path("offers/", OffersView.as_view(), name= "offers"), #for laptops and TV
    path("offers2/", OffersView2.as_view(), name= "offers2"), #OffersView2
    path("offers3/",OffersView3.as_view(), name="offers3"), # for home appliances  
    path("all-products/",all_product_view,name="allproducts"),   #to show All Laptops
    path("all-products2/",all_product_view2,name="allproducts2"),   #to show All TVs
    path("all-products3/",all_product_view3,name="allproducts3"),   #to show All home appliances 
    path("all-products4/",all_product_view4,name="allproducts4"),   #to show All mobiles
    path("all-products5/",all_product_view5,name="allproducts5"),   #to show All  tablets
    path("all-products6/",all_product_view6,name="allproducts6"),   #to show All bestseller
    path("all-products7/",all_product_view7,name="allproducts7"),   #to show All fashion
    path("all-products8/",all_product_view8,name="allproducts8"),   #to show All tools
    
    
]

orderapp/urls.py
from django.urls import path

from orderapp.views import (Add_to_Shoping_cart,
OrderCart,Order_showing, Order_Product_showing,
cart_details, cart_delete, user_order_details, userorderproduct_details)

app_name="orderapp"

urlpatterns=[
    path('addingcart/<int:id>/', Add_to_Shoping_cart, name='Add_to_Shoping_cart'),
    path("cart_details/" ,cart_details, name="cart_details"),
    path('cart_delete/<int:id>/', cart_delete, name='cart_delete'),
    path("order_cart/",OrderCart,name="OrderCart"),
    path("orderlist",Order_showing,name="orderlist"),
    path('OrderProduct/', Order_Product_showing, name="orderproduct"),
    path('OrderDetails/<int:id>/',user_order_details,name='user_order_details'),
    path('OrderproductDetails/<int:id>/<int:oid>/',userorderproduct_details,name='userorderproduct_details'),
    
    
]

ecomapp/forms.py
from django import forms
from ecomapp.models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Name & Sure name'}),
            'email': forms.EmailInput(attrs={'class': 'input', 'placeholder': 'Write your email'}),
            'subject': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Wrte your Subjects'}),
            'message': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Write your messages'}),
        }


class SearchForm(forms.Form):
    query=forms.CharField(max_length=200)
    cat_id = forms.IntegerField(max_value=6)





  

ecomapp/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from ecomapp.models import *
from product.models import *
from django.contrib import messages
from .forms import *
from django.views.generic import  TemplateView
from django.urls import reverse
import product
from orderapp.models import *
from django.core.mail import send_mail
from django.utils.translation import gettext as _
from django.core.paginator import Paginator
from idlelib import query


# Create your views here.
def home(request):
        #from django.utils import translation
       # user_language= 'ar'
        #tranlation.activate=(user_language)
        #if translation.LANGUAGE_SESSION_KEY in request.session:    
               # del request.session[translation.LANGUAGE_SESSION_KEY]  
        
        current_user = request.user
        cart_product= ShopCart.objects.filter(user_id=current_user.id)
        total_amount = 0
        for p in cart_product:
            if p.product.discount_price:
                total_amount += p.product.discount_price * p.quantity
            elif p.product.price:
                    
                total_amount += p.product.price * p.quantity
                        
          
        category= Category.objects.all()
        
        setting = Setting.objects.get(id=1)
        sliding_images = Product.objects.all().order_by('-id')  [:9]
        latest_products = Product.objects.all().order_by("-id")
        
        products = Product.objects.all().order_by("id")
        fashionproducts=Product.objects.all().order_by("id")
        
        context={"setting":setting,
                "sliding_images":sliding_images,
            "latest_products":latest_products,
            "products":products,
            "category":category,
            "cart_product":cart_product,
                "total_amount":total_amount,
              
               
            }
   
        return render(request, "home.html", context)


def about(request):
        setting = Setting.objects.get(id=1)
        category= Category.objects.all()
        context={"setting":setting,
        "category":category,}
        return render(request,"about.html", context)


def contact(request):

        if request.method == 'POST':
                form = ContactForm(request.POST)
                if form.is_valid():
                        data = ContactMessage()
                        data.name = form.cleaned_data['name']
                        data.email = form.cleaned_data['email']
                        data.subject = form.cleaned_data['subject']
                        data.message = form.cleaned_data['message']
                        data.ip = request.META.get('REMOTE_ADDR')
                        data.save()
                        #messages.success(request, 'Profile details updated.')
                        return redirect('contact_dat')
        setting = Setting.objects.get(pk=1)
        category= Category.objects.all()
        form = ContactForm
        context = {
                        'setting': setting,
                        'form': form,
                        "category":category,
                }
        messages.success(request, 'Your message was successfully sent.')
        return render (request, "contact_form.html", context )
                


class SingleProductView(TemplateView):
        model = Product
        template_name = "product-single.html"
        def get_context_data(self, **kwargs):
                context= super().get_context_data(**kwargs)
                url_slug = self.kwargs["slug"]
                single_product = Product.objects.get(slug=url_slug)
                single_product.view_count+=1
                setting= Setting.objects.get(id=1)
                images = Images.objects.filter(product__slug=url_slug)
                products = Product.objects.all().order_by("id")[:5]
                
#                comment_show = Comment.objects.filter(product_id=id, status='True')
                category= Category.objects.all()
               
                single_product.save()
                single_product.min_amount==1
                context={"setting":setting,
                "single_product":single_product,
                "images":images,
                "category":category,
                #"comment_show":comment_show,
                "products":products,
                "single_product.view_count":single_product.view_count,
               
                
                }
                return context
                '''
                if single_product.variant != "None":  # Product have variants

                        if self.request.method == 'POST':  # if we select color
                                variant_id = self.request.POST.get('variantid')
                                variant = Variants.objects.get(id=variant_id)  # selected product by click color radio
                                colors = Variants.objects.filter(product_id=id, size_id=variant.size_id)
                                sizes = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY size_id', [id])
                                query += variant.title+' Size:' + str(variant.size) + ' Color:' + str(variant.color)
                        else:
                                variants = Variants.objects.filter(product_id=id)
                                colors = Variants.objects.filter(product_id=id, size_id=variants[0].size_id)
                                sizes = Variants.objects.raw('SELECT * FROM  product_variants  WHERE product_id=%s GROUP BY size_id', [id])
                                variant = Variants.objects.get(id=variants[0].id)
                                context.update({'sizes': sizes, 'colors': colors,
                                        'variant': variant, 'query': query
                                        })'''
               


def ajaxcolor(request):
    data = {}
    if request.POST.get('action') == 'post':
        size_id = request.POST.get('size')
        productid = request.POST.get('productid')
        colors = Variants.objects.filter(product_id=productid, size_id=size_id)
        context = {
            'size_id': size_id,
            'productid': productid,
            'colors': colors,
        }
        data = {'rendered_table': render_to_string('color_list.html', context=context)}
        return JsonResponse(data)
    return JsonResponse(data)






def category_product(request,id, slug):
        category= Category.objects.all()
        setting= Setting.objects.get(id=1)
        sliding_images = Product.objects.all().order_by('id')  [:3]
        product_cat=Product.objects.filter(category_id=id)
        products = Product.objects.all().order_by("id")[:5]
        page_number = request.GET.get('page')
        paginator = Paginator(products, 3)
        product_list = paginator.get_page(page_number)
        paginate_by= 3
        context={"product_cat":product_cat,
                "sliding_images":sliding_images,
                "setting":setting,
                "category":category,
        }
                      
        return render(request,"category_product.html",context)



def searchview(request):
        if request.method=="GET":
                form=SearchForm(request.GET)  
                if form.is_valid():
                        query = form.cleaned_data['query']
                        cat_id = form.cleaned_data['cat_id']
                        if cat_id == 0:
                                products = Product.objects.filter(title__icontains=query)
                        else:
                                products = Product.objects.filter(
                                        title__icontains=query, category_id=cat_id
                                )
                        category = Category.objects.all()
                        setting= Setting.objects.get(id=1)
                        sliding_images = Product.objects.all().order_by('id')  [:4]
                        context = {
                                "category":category,
                                "query":query,
                                "product_cat":products,
                                "setting":setting,
                                "sliding_images":sliding_images,
                        }
                        return render (request, "category_product.html", context)
        return HttpResponseRedirect("category_product")

def Faq_details(request):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    faq = FAQ.objects.filter(status=True).order_by('created_at')

    context = {
        'category': category,
        'setting': setting,
        'faq': faq

    }
    return render(request, 'faq.html', context)



def send(request):
        send_mail("Hello","Hello there. this is automated message!","nemhfa@gmail.com",["efaried@icloud.com"],fail_silently=False)
        return (request,"send_email.hmtl")




class OffersView(TemplateView): #for Tv,laptops
    paginate_by= 8
    model=Product
    
    template_name = "offers.html"
    
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        products=Product.objects.all().order_by("name")
        page_number = self.request.GET.get('page')
        paginator = Paginator(products, 8)
        product_list = paginator.get_page(page_number)
        category= Category.objects.all()
        setting= Setting.objects.get(id=1)
        faq = FAQ.objects.filter(status=True).order_by('created_at')
        
        
        context={
                'products':products,
                'category': category,
                'setting': setting,
                'faq': faq,
                'product_list':product_list,
        }
        return context



class OffersView2(TemplateView): #mobiles
    paginate_by= 4
    model=Product
    
    template_name = "offers2.html"
    
    

ecomapp/templates/header.html
{% load static %}
{% load humanize %}
{% load i18n %}


    <header class="li-header-4">
        <!-- Begin Header Top Area -->
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <!-- Begin Header Top Left Area -->
                    <div class="col-lg-3 col-md-4">
                        <div class="header-top-left">
                            <ul class="phone-wrap">
                                <li><span>{%trans  'Telephone Enquiry' %}:</span><a href="#">(+2){{setting.phone}}</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Header Top Left Area End Here -->
                    <!-- Begin Header Top Right Area -->
                    <div class="col-lg-9 col-md-8">
                        <div class="header-top-right">
                            <ul class="ht-menu">
                                <!-- Begin Setting Area -->
                                <li>
                                    <div class="ht-setting-trigger"><span>{% trans 'My Account' %}</span></div>
                                    <div class="setting ht-setting">
                                        <ul class="ht-setting-list">
                                            {% if request.user.is_authenticated %}
                                            <li><a href="#">Hi {{request.user.username}}</a></li>
                                            <li><a href="{% url 'UserApp:userprofile' %}">{%  trans  'My profile' %}</a></li>
                                            <li><a href="{% url 'orderapp:OrderCart' %}">{%  trans 'Checkout' %} </a></li>
                                            <li><a href="{% url 'UserApp:user_logout' %}">{% trans 'Logout' %}</a></li>
                                            {% else %}
                                            <li><a href="{% url 'UserApp:user_login' %}">{% trans 'Login' %}</a></li>
                                            <li><a href="{% url 'UserApp:user_register' %}">{% trans 'Register as a New customer?!' %}</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </li>
                                <!-- Setting Area End Here -->
                                <!-- Begin Currency Area -->
                                <li>
                                    <span class="currency-selector-wrapper">{% trans 'Currency' %} :</span>
                                    <div class="ht-currency-trigger"><span>EGP</span></div>
                                    <div class="currency ht-currency">
                                        <ul class="ht-setting-list">
                                            <li><a href="#">EGP</a></li>
                                            <li class="active"><a href="#">USD $</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <!-- Currency Area End Here -->
                                <!-- Begin Language Area -->
                                <li>
                                    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                                        {% get_current_language as LANGUAGE_CODE %}                                         
                                        <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                                        
                                        {% if LANGUAGE_CODE == 'ar' %}
                                            <button type='submit' name='language' value='en' class="icon solid fa-language">
                                                <span class="label"></span>English
                                            </button>
                                        {% else %}
                                            <button type='submit' name='language' value='ar' class="icon solid fa-language">
                                                <span class="label"></span>عربي
                                            </button>
                                        {% endif %}
                                    </form>
                                </li>
                                <!-- Language Area End Here -->
                            </ul>
                        </div>
                    </div>
                    <!-- Header Top Right Area End Here -->
                </div>
            </div>
        </div>
        <!-- Header Top Area End Here -->
        <!-- Begin Header Middle Area -->
        <div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
            <div class="container">
                <div class="row">
                    <!-- Begin Header Logo Area -->
                    <div class="col-lg-3">
                        <div class="logo pb-sm-30 pb-xs-30">
                            <a href="{% url 'ecomapp:home' %}">
                                <img src="{{setting.icon.url}}" style="height: 50px; width: 50px;" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- Header Logo Area End Here -->
                    <!-- Begin Header Middle Right Area -->
                    <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
                        <!-- Begin Header Middle Searchbox Area -->
                        <form action="{% url 'ecomapp:searchview' %}" class="hm-searchbox"  method="GET"  >
                            {% csrf_token %}
                            <select   name="cat_id" class="nice-select select-search-category">

                                <option value="0">All</option>   
                                
                                {% load mptt_tags %}
                                {% recursetree category %}
                                
                                <option value="10">{{ node.title }}</option> 
                                {% if not node.is_leaf_node %}                    
                                <option value="17">{{ children }}</option>                    
                                {% endif %}
                                {% endrecursetree %}
                            </select>
                            <input type="text" placeholder="Enter your search key ..." id="query"     name="query">
                            <button class="li-btn" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                        <!-- Header Middle Searchbox Area End Here -->
                        <!-- Begin Header Middle Right Area -->
                        <div class="header-middle-right">
                            <ul class="hm-menu">
                                <!-- Begin Header Middle Wishlist Area -->
                                
                                <!-- Header Middle Wishlist Area End Here -->
                                <!-- Begin Header Mini Cart Area -->
                                <li class="hm-minicart">
                                    <div class="hm-minicart-trigger">
                                        <span class="item-icon"></span>
                                        <span class="item-text">EGP{{total_amount|intcomma}}
                                            <span class="cart-item-count">{{cart_product.count}}</span>
                                        </span>
                                    </div>
                                    <span></span>
                                    <div class="minicart">
                                        <ul class="minicart-product-list">
                                            {% for p in cart_product %}
                                              
                                            
                                            <li>
                                                <a href="single-product.html" class="minicart-product-image">
                                                    <img src="{{ p.product.ImageUrl }}" alt="cart products">
                                                </a>
                                                <div class="minicart-product-details">
                                                    <h6><a href="single-product.html">{{p.product.title}}</a></h6>
                                                    <span><span class="amount">{% if p.product.discount_price %}
                                                        <span class="mr-1" style="color:red;">
                                                         <del>EGP{{ p.product.price|intcomma }}</del>
                                                        </span>
                                                         <span>EGP{{ p.product.discount_price|intcomma }} * {{p.quantity}}</span>
                                                    {% else %}
                                                        <span>EGP{{ p.product.price|intcomma }}* {{p.quantity}}</span>
                                                    {% endif %}</span></td></span>
                                                </div>
                                                <button class="close">
                                                    <i class="fa fa-close"></i>
                                                </button>
                                            </li>
                                            {% endfor %}
                                           
                                        </ul>
                                        <p class="minicart-total">{% trans 'subtotal' %}: <span>EGP{{total_amount|intcomma}}</span></p>
                                        <div class="minicart-button">
                                            <a href="{% url 'orderapp:cart_details'  %}" class="li-button li-button-dark li-button-fullwidth li-button-sm">
                                                <span>{% trans 'View Full Cart' %}</span>
                                            </a>
                                            <a href="{% url 'orderapp:OrderCart' %}" class="li-button li-button-fullwidth li-button-sm">
                                                <span>{% trans 'checkout' %}</span>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <!-- Header Mini Cart Area End Here -->
                            </ul>
                        </div>
                        <!-- Header Middle Right Area End Here -->
                    </div>
                    <!-- Header Middle Right Area End Here -->
                </div>
            </div>
        </div>
        <!-- Header Middle Area End Here -->
        <!-- Begin Header Bottom Area -->
        <div class="header-bottom header-sticky stick d-none d-lg-block d-xl-block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                       <!-- Begin Header Bottom Menu Area -->
                       <div class="hb-menu">
                           <nav>
                               <ul>
                                   <li ><a href="{% url 'ecomapp:home' %}">{% trans 'Home' %}</a>
                                       
                                   </li>
                                   
                                   <li><a href="{% url 'ecomapp:about' %}">{% trans 'About Us' %}</a></li>
                                   <li><a href="{% url 'ecomapp:coantact_dat' %}">{% trans 'Contact Us' %}</a></li>
                                   <li><a href="{% url 'ecomapp:Faq_details' %}">{% trans 'FAQ' %}</a></li>
                                   
                                   
                               </ul>
                           </nav>
                       </div>
                       <!-- Header Bottom Menu Area End Here -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Header Bottom Area End Here -->
        <!-- Begin Mobile Menu Area -->
        <div class="mobile-menu-area mobile-menu-area-4 d-lg-none d-xl-none col-12">
            <div class="container"> 
                <div class="row">
                    <div class="mobile-menu">
                    </div>
                </div>
            </div>
        </div>
        <!-- Mobile Menu Area End Here -->
    </header>

ecomapp/templates/offers2.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% load humanize %}


{% block style %}{% endblock  %}
{% block title %}  Single Product  {% endblock %}
{% block description %}     {% endblock %}
{% block keywords %}        {% endblock %}   
 

           {% block header %}
             {% include "header.html" %}
           {% endblock  %}

{% block another_content %}

<div class="container">
    <div class="row">
        <section class="text-center mb-4" style=background-color:F0FFFF >

            <div class="row wow fadeIn">
    
              {% for p in products %}
              {% if p.name1 == "mobile"  %}
              <div class="col-lg-3 col-md-6 card ">
    
                <div class="card  border-0 ">
    
                  <div class="view overlay">
                    
                    
    
                    {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="img-fluid> {% endcomment %}
                    <a href="{% url 'ecomapp:product_single' p.slug %}"><img src="{{ p.image.url}}" class="card-img-top" style="height: 250px;object-fit:contain; " > </a>
                    <h5 class="pt-2" >
                      
                      <a href="{% url 'ecomapp:product_single' p.slug %}" class="dark-grey-text  " style="text-decoration: none;" >{{ p.title|truncatechars:50 }}</a>
                      
                    
                  </h5>
                        
                      <div class="mask rgba-white-slight"></div>
                   
                  </div>
    
                  <div class="card-body text-center">
                    
                      <h5 class="grey-text">{{ p.category}}</h5>
                   
                    
                    <h4 class="font-weight-bold blue-text">
                      <p class="lead">
                        {% if p.discount_price %}
                        <span class="mr-1">
                          <del style="color:blue;">EGP{{ p.price }}</del>
                        </span>
                        <span style="color:red;">EGP{{ p.discount_price|intcomma }}</span>
                        {% else %}
                        <span style="color:red;">EGP{{p.price|intcomma }}</span>
                        {% endif %}
                      </p>
                      <a href="{% url 'orderapp:Add_to_Shoping_cart' id=p.id %}" class="btn btn-primary">Add To Cart</a>
                      
                      </strong>
                    </h4>
    
                  </div>
    
                </div>
    
              </div>
              {% endif %}
              {% endfor %}
                
              
            </div>
    
          </section><hr>
          <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">
    
              {% if product_list.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
              {% endif %}
                {% for i in product_list.paginator.page_range %}
                {% if i == product_list.number %}
              <li class="page-item active"><a class="page-link" >{{ i}}</a></li>
              {% else %}
              <li class="page-item "><a class="page-link" href="?page={{ i }}">{{ i}}</a></li>
              {% endif %}
    
              {% endfor %}
    
              {% if product_list.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
              {% endif %}
            </ul>
          </nav>
    </div>
    
</div>




{% endblock another_content %}

{% block footer %}
            {% include "footer.html" %}
 {% endblock  %}