EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    
    path(_('admin/'), admin.site.urls),
    path(_(''),include("ecomapp.urls",namespace="ecomapp")),
    path('order/',include('orderapp.urls',namespace="orderapp")),
    path('user/',include('UserApp.urls',namespace="UserApp")),
    path("product/",include("product.urls",namespace="product")),
        
    )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from UserApp.views import user_logout, user_login, user_register, user_update, user_password,usercomment, comment_delete
from UserApp.views import usrprofiledata
app_name='UserApp'

urlpatterns = [
    path('logout/',user_logout, name='user_logout' ),
    path('login/',user_login, name='user_login' ),
    path('register/',user_register, name='user_register' ),
    path('userprofile/',usrprofiledata, name='userprofile' ),
    path('user_update/',user_update, name='user_update' ),
    path('password_update/',user_password, name='user_password' ),
    path('user_comment/',usercomment, name='usercomment' ),
    path('comment_delete/<int:id>/',comment_delete, name='comment_delete' ),
]

ecomapp/urls.py
from django.urls import path

from .views import *

app_name= "ecomapp"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("contact/",contact, name="coantact_dat"),
    path("product/<slug:slug>/", SingleProductView.as_view(), name="product_single"),
    path("product/<int:id>/<slug:slug>/", category_product, name="category_product"),
    path("search/",searchview,name="searchview"),
    path("faq/",Faq_details,name="Faq_details"),
    path("send/",send,name="send"),
    path("offers/", OffersView.as_view(), name= "offers"), #for laptops and TV
    path("offers2/", OffersView2.as_view(), name= "offers2"), #OffersView2
    path("offers3/",OffersView3.as_view(), name="offers3"), # for home appliances  
    path("all-products/",all_product_view,name="allproducts"),   #to show All Laptops
    path("all-products2/",all_product_view2,name="allproducts2"),   #to show All TVs
    path("all-products3/",all_product_view3,name="allproducts3"),   #to show All home appliances 
    path("all-products4/",all_product_view4,name="allproducts4"),   #to show All mobiles
    path("all-products5/",all_product_view5,name="allproducts5"),   #to show All  tablets
    path("all-products6/",all_product_view6,name="allproducts6"),   #to show All bestseller
    path("all-products7/",all_product_view7,name="allproducts7"),   #to show All fashion
    path("all-products8/",all_product_view8,name="allproducts8"),   #to show All tools
    
    
]

orderapp/urls.py
from django.urls import path

from orderapp.views import (Add_to_Shoping_cart,
OrderCart,Order_showing, Order_Product_showing,
cart_details, cart_delete, user_order_details, userorderproduct_details)

app_name="orderapp"

urlpatterns=[
    path('addingcart/<int:id>/', Add_to_Shoping_cart, name='Add_to_Shoping_cart'),
    path("cart_details/" ,cart_details, name="cart_details"),
    path('cart_delete/<int:id>/', cart_delete, name='cart_delete'),
    path("order_cart/",OrderCart,name="OrderCart"),
    path("orderlist",Order_showing,name="orderlist"),
    path('OrderProduct/', Order_Product_showing, name="orderproduct"),
    path('OrderDetails/<int:id>/',user_order_details,name='user_order_details'),
    path('OrderproductDetails/<int:id>/<int:oid>/',userorderproduct_details,name='userorderproduct_details'),
    
    
]

UserApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django_countries.fields import CountryField
from django.core.mail import send_mail
# Create your models here.
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone=models.CharField(max_length=20,blank=True, null=True)
    email=models.EmailField(blank=True, null=True)
    address=models.CharField(max_length=200,blank=True, null=True)
    address_ar =models.CharField(max_length=200,blank=True, null=True)
    city=models.CharField(max_length=100,blank=True, null=True)
    city_ar=models.CharField(max_length=100,blank=True, null=True)
    country=models.CharField(max_length=200,null=True)
    country_ar=models.CharField(max_length=200,null=True)
    image=models.ImageField(upload_to='user_image',blank=True, null=True)

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + '' +self.user.last_name +'['+self.user.username+']'

    def  image_tag(self):
    	 return mark_safe('<img src="{}" heights="50" width="50" />'.format(self.image.url))
    image_tag.short_description='Image'

    def imageUrl(self):
        if self.image:
            return self.image.url
        else:
            return""

    

UserApp/forms.py
from django import forms
from django.contrib.auth.models import  User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.forms import ModelForm, TextInput, PasswordInput, EmailInput, NumberInput, Select, FileInput
from .models import UserProfile



class SingUpForm(UserCreationForm):
    username=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'pa=laceholder':'Write your username.'}))
    email=forms.EmailField(max_length=200, widget=forms.EmailInput(attrs={'placeholder':'Write your Email.'}))
    first_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'pa=laceholder':'Write your First_name.'}))
    last_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'pa=laceholder':'Write your last_name.'}))

    class Meta:
        model=User
        fields=["username","email","first_name","first_name","password1","password2"]
        widgets={
            "password1":forms.PasswordInput(attrs={'placeholder':'enter your password here', "class":"form-control"}),
            "password2":forms.PasswordInput(attrs={'placeholder':'enter your password again', "class":"form-control"}),
        }


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }


CITY = [
    ('Cairo', 'Cairo'),
    ('Alixandria', 'Alixandria'),
    ('Ismailia', 'Ismailia'),
    ('Portsied', 'Portsied'),
    ('Damita', 'Damita'),
    ('Suez', 'Suez'),
    ('Alaqsour', 'Alaqsour'),
    ('KaferElshikh', 'KaferElshikh'),
    ('Fayoun', 'Fayoun'),
    ('Sohag', 'Sohag'),
    ('Aswan', 'Aswan'),
    ('Asiot', 'Asiot'),
    ('Qena', 'Qena'),
    ('Behera', 'Behera'),
   ('ٌRedSea', 'ٌRedSea'),
   ('Monofiah', 'Monofiah'),
   ('Menea', 'Menea'),
   ('Matrooh', 'Matrooh'),
   ('Wady Gadid', 'Wady Gadid'),
   ('Qaleubiah', 'Qaleubiah'),
   ('Gharbiah', 'Gharbiah'),
   ('shamal Sinaa', 'shamal Sinaa'),
   ('Sharquiah', 'Sharquiah'),
   ('Daqahliah', 'Daqahliah'),
   ('Giza', 'Giza'),
   ('Janoob Sinaa', 'Janoob Sina'),
   ('Banysweef', 'Banysweef'),

]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image', }),
        }

UserApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout,authenticate, login,update_session_auth_hash
from product.models import Category,Comment,Product
from ecomapp.models import Setting
from django.contrib import messages
from .forms import SingUpForm, UserUpdateForm, ProfileUpdateForm
from UserApp.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext as _
# Create your views here.

def user_login(request):
    
    if request.method== 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('ecomapp:home')
      
        else:
            messages.error(request, 'Invalid password or username!,Please try again.')
            # Return an 'invalid login' error message.

    category= Category.objects.all()
    setting = Setting.objects.get(id=1)
    context={"setting":setting,
                "category":category,
     
     }    
    return render(request,'user_login.html',context)



@login_required
def user_logout(request):
    logout(request)
    return redirect('ecomapp:home')


def user_register(request):
    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password_raw = form.cleaned_data.get('password1')
            email=form.cleaned_data.get('email')
            user = authenticate(username=username, password=password_raw,email=email)
            login(request, user)
            current_user = request.user
            data=UserProfile()
            data.user_id=current_user.id
            data.image="user_image/avatar.jpg"
            data.save()
            messages.warning(request, "Your Account has been created successfuly")
            return redirect('UserApp:user_login')
        else:
            form = SingUpForm()
    else:
        form = SingUpForm()
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    context = {'category': category,
               'setting': setting,
               'form': form}
    return render(request, 'user_register.html', context)


@login_required
def usrprofiledata(request):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user= request.user
    profile=UserProfile.objects.get(user_id=current_user.id)

    context={"setting":setting,
                "category":category,
                "profile":profile,
     
     } 
    return render(request, 'userprofile.html', context)


@login_required
def user_update(request):
    if request.method=="POST":
        user_form= UserUpdateForm(request.POST, instance=request.user)
        profile_form= ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile )
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile details updated.')
            return redirect("UserApp:userprofile")
    else:
        user_form= UserUpdateForm(instance=request.user)
        profile_form= ProfileUpdateForm(instance=request.user.userprofile )
        category = Category.objects.all()
        setting = Setting.objects.get(id=1)
        context={"setting":setting,
                "category":category,
        "user_form":user_form,
            "profile_form":profile_form,
            
            }
    return render(request, "userupdate.html", context)


@login_required()
def user_password(request):
    if request.method == "POST":
        form=PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user= form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'your password was successfuly updated!.')
            return redirect("UserApp:userprofile")
        else:
            messages.error(request, 'Please correct the error below!.<br>')
            return redirect("UserApp:user_password")
    else:
        category = Category.objects.all()
        setting = Setting.objects.get(id=1)
        form=PasswordChangeForm(request.user)
        context={"setting":setting,
                "category":category,
                "form":form,
                }
        return render(request,"userpasswordupdate.html",context)

@login_required()
def usercomment(request):
    category = Category.objects.all()
    setting = Setting.objects.get(id=1)
    current_user=request.user
    comment=Comment.objects.filter(user_id=current_user.id)

    context={"setting":setting,
                "category":category,
                "comment":comment,
                }
    return render(request,"usercomment.html",context)


def comment_delete(request,id):
   
    current_user=request.user
    comment=Comment.objects.filter(user_id=current_user.id,id=id)
    comment.delete()
    messages.success(request, 'your message was successfuly deleted!.')
    return redirect("UserApp:usercomment")

    

UserApp/templates/user_login.html
{% extends "index.html" %}
{% load i18n %}
{% load static %}

{% block style %}{% endblock  %}
{% block title %}  Login {% endblock %}
{% block description %}     {% endblock %}
{% block keywords %}        {% endblock %}   
 

           {% block header %}
             {% include "header.html" %}
           {% endblock  %}

{% block another_content %}
              


<div>
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{message}}
    </div>
    {% endfor %}{% endif %}
</div>

  <div class="page-section mb-60">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6 mb-30">
                <!-- Login Form s-->
                <form action="{% url 'UserApp:user_login' %}" method="POST" >
                    {% csrf_token %}
                    <div class="login-form">
                        <h4 class="login-title">{% trans 'Login' %}</h4>
                        <div class="row">
                            <div class="col-md-12 col-12 mb-20">
                                <label>{% trans 'Username ' %}*</label>
                                <input class="mb-0" type="text" placeholder="username"  name="username">
                            </div>
                            <div class="col-12 mb-20">
                                <label>{% trans 'Password' %}</label>
                                <input class="mb-0" type="password" placeholder="Password" name="password">
                            </div>
                            <div class="col-md-8">
                                <div class="check-box d-inline-block ml-0 ml-md-2 mt-10">
                                    <input type="checkbox" id="remember_me">
                                    <label for="remember_me">{% trans 'Remember me' %}</label>
                                </div>
                            </div>
                            <div class="col-md-4 mt-10 mb-20 text-left text-md-right">
                                <a href="#"> {% trans 'Forgotten pasward?' %}</a><br>
                                <a href="{% url 'UserApp:user_register' %}"> {% trans  'Register as a New customer?!' %}</a>
                            </div>
                            <div class="col-md-12">
                                <button class="register-button mt-0">{% trans 'Login' %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>


{% endblock another_content %}

{% block footer %}
            {% include "footer.html" %}
 {% endblock  %}

UserApp/templates/user_panel.html
{% load static %}
{% load humanize %}
{% load i18n %}





<div class="aside">
    <ul class="list-links">
        <li><a href="{% url 'UserApp:userprofile' %}">{% trans 'User Profile' %}</a></li>
        <li><a href="{%url 'orderapp:orderlist'%}">{% trans 'My Orders' %}</a></li>
        <li><a href="{%url 'orderapp:orderproduct'%}">{% trans 'Order Products' %}</a></li>
        <li><a href="{%url 'UserApp:usercomment'%}">{% trans 'My Comments' %}</a></li>
        
        
        
        <li><a href="{% url 'UserApp:user_logout' %}">{% trans 'Logout' %}</a></li>
    </ul>
</div>

UserApp/templates/user_register.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block style %}{% endblock  %}
{% block title %}  Register {% endblock %}
{% block description %}     {% endblock %}
{% block keywords %}        {% endblock %}   
 

           {% block header %}
             {% include "header.html" %}
           {% endblock  %}

{% block another_content %}
              




  <div class="page-section mb-60">
    <div class="container">
        <div class="row">
            
            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                <form action="{% url 'UserApp:user_register' %}" method="POST">
                    {% csrf_token %}
                    <div class="login-form">
                        <h4 class="login-title">{% trans 'Register' %}</h4>
                        <div class="row">
                            <div class="col-md-6 col-12 mb-20">
                                {{ form.username|as_crispy_field }}
                            </div>
                            <div class="col-md-6 col-12 mb-20">
                                {{ form.first_name|as_crispy_field }}
                            </div>
                            <div class="col-md-6 col-12 mb-20">
                                {{ form.last_name|as_crispy_field }}
                            </div>
                            <div class="col-md-12 mb-20">
                                {{ form.email|as_crispy_field }}
                            </div>
                            <div class="col-md-6 mb-20">
                                {{ form.password1|as_crispy_field }}
                            </div>
                            <div class="col-md-6 mb-20">
                                {{ form.password2|as_crispy_field }}
                            </div>
                            <div class="col-12">
                                
                                
                                <button class="register-button mt-0">{% trans 'Register' %}</button>
                            </div>
                            <div class="col-12">
                                
                                <a href="{% url 'UserApp:user_login' %}">{% trans 'Already have an account?Login from here' %}</a>
                                
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock another_content %}

{% block footer %}
            {% include "footer.html" %}
 {% endblock  %}

UserApp/templates/usercomment.html
{%extends 'index.html'%}
{% load i18n %}
{%load static%}

{% load crispy_forms_tags %}

{% block titlee %}
Usercomment

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}



 <div id="breadcrum">
     <div class="container">
         <div>
             <ul class="breadcrumb">
                 <li> <a href="">{% trans 'Home' %}</a></li>
                 >>
                 <li class="active">{% trans 'User Comment' %}</li>
             </ul>

         </div>

     </div>

 </div>



 <div class="section">
     <div class="container">

         {%if messages %}

         {% for message in messages %}
         <div class="alert alert-{{ message.tags }}" role="alert">
             {{message}}
         </div>
         {% endfor %}
         {% endif %}

         <!--start from here-->
         <div class="page-section mb-60">
             <div class="container">
                 <div class="row">
                     <div class="col-sm-12 col-md-12 col-xs-12 col-lg-3 mb-30">
                         <h1 class="font-weight-bold">{% trans 'User Panel' %}</h1>
                        {% include 'user_panel.html' %} 
                     </div>

                     <div class="col-sm-12 col-md-12 col-lg-9 col-xs-12">
                           <h1 class="text-center font-weight-bold">{% trans 'User Comments' %}</h1>
                     <table class="shopping-cart-table table">
                               <thead>
                                   <tr>
                                       <th class="text-center">{% trans 'Item Image' %}</th>
                                       <th class="text-center">{% trans 'Product Name' %} </th>
                                       <th class="text-center">{% trans 'Comment Title' %}</th>
                                       <th class="text-center">{% trans 'Comment' %}</th>
                                       <th class="text-center">{% trans 'Comment Status' %} </th>
                                       <th class="text-center">{% trans 'Comment Date' %}</th>
                                       <th class="text-center">{% trans 'Action' %}</th>
                                    
                                       
                                   </tr>
                               </thead>
                               <tbody>
                                   {%for p in comment%}
                                   <tr>
                                       <td class="thumb text-center"><a href=""><img src="{{p.product.ImageUrl}}" alt="" height="30px"></a></td>
                                       <td class="text-center"><a href="">{{p.product.title}}</a></td>
                                       <td class="price text-center">{{p.subject}}</td>
                                       <td class="status text-center">{{p.comment}}</td>
                                       <td class="created text-center">{{p.status}}</td>
                                       <td class="created text-center">{{p.created_at}}</td>
                                       <td class="pull-right"><button class="btn btn-danger">
                                        <a href="{%url 'UserApp:comment_delete' id=p.id%}" onclick="return confirm('Are You sure delete your comment?')">
                                            Delete
                                            </a>
                                            </button></td>
                                   

                                   
                                   </tr>
                                   {%endfor%}
                                   
                               </tbody>
                           </table>

                    </div>
                 </div>

                 <!--end from here-->

             </div>
         </div>


{% endblock another_content %}




{% block footer %}

{% include "footer.html" %}

{% endblock footer %}

UserApp/templates/userpasswordupdate.html
{%extends 'index.html'%}
{% load i18n %}
{%load static%}

{% load crispy_forms_tags %}

{% block titlee %}
User-Pssword-Update

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}




<div id="breadcrum">
    <div class="container">
        <div>
            <ul class="breadcrumb">
                <li> <a href="{%url 'ecomapp:home'%}">{% trans 'Home' %}</a></li>
                >>
                <li class="active">{% trans 'User Update' %}</li>
            </ul>

        </div>

    </div>

</div>

<!-- /BREADCRUMB -->


<!-- row -->
<div class="page-section mb-60">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-3 mb-30">
                <h1 class="font-weight-bold">{% trans 'User Panel' %}</h1>
                
            </div>

            <div class="col-sm-12 col-md-12 col-lg-9 col-xs-12">
                <div class="billing-details">
                    <div>

                        {% if messages %}
                        {% for message in messages %}
                        <div style="color: #d43f3a; font-size: medium">
                            {{ message|safe }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <h1 class="text-center font-weight-bold">{% trans 'Update your Information' %}</h1>
                </div>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form.as_p  }}
                       
                    </fieldset>
                    <div class="form-group">
                        <button class="primary-btn" type="submit">{% trans 'Update' %}</button>
                    </div>
                </form>

            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->




{% endblock another_content %}




{% block footer %}

{% include "footer.html" %}

{% endblock footer %}

UserApp/templates/userprofile.html
{%extends 'index.html'%}

{%load static%}

{% load i18n %}

{% block titlee %}
single product

{% endblock titlee %}



{% block description %}
{{setting.description}}

{% endblock description %}


{% block keyword %}

{% endblock keyword %}



{% block header %}
{% include "header.html" %}
{% endblock header %}


{% block another_content %}


<div id="breadcrum">
    <div class="container">
        <div>
               
            </ul>

        </div>

    </div>

</div>



<div class="section">
    <div class="container">

        {%if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        <!--start from here-->
        <div class="page-section mb-60">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-xs-12 col-lg-3 mb-30">
                        <h1 class="font-weight-bold">{% trans 'User Panel' %}</h1>
                        {% include 'user_panel.html' %}
                        
                    </div>

                    <div class="col-sm-12 col-md-12 col-lg-9 col-xs-12">
                        <h1 class="text-center font-weight-bold">{% trans 'User Details' %}</h1>
                        <table class="shopping-cart-table table">
                            <tr>
                                <th class="text-left">
                                    <a href="{%url 'UserApp:user_update'%}" class="primary-btn">{% trans 'Update Profile' %}</a>
                                    &nbsp; &nbsp; &nbsp;
                                    <a href="{% url 'UserApp:user_password' %}" class="primary-btn">{% trans 'Change Password' %}</a>
                                </th>
                                <td><img src="{{ profile.imageUrl}}"
                                        style="border-radius:10px; height: 100px;width:100px; ">
                                </td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'Name Surname :' %}</th>
                                <td class="text-left">{{ user.username}} {{ user.last_name}} </td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'Email' %}</th>
                                <td class="text-left">{{ profile.user.email}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'Phone' %}</th>
                                <td class="text-left">{{ profile.phone}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'Addres' %}</th>
                                <td class="text-left">{{ profile.address}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'City' %}</th>
                                <td class="text-left">{{ profile.city}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">{% trans 'Country' %}</th>
                                <td class="text-left">{{ profile.country}}</td>
                            </tr>

                        </table>
                    </div>
                </div>

                <!--end from here-->

            </div>
        </div>



        {% endblock another_content %}




        {% block footer %}

        {% include "footer.html" %}

        {% endblock footer %}